const COPY = {
  en: {
    "meta.title": "Ataberk Kılınçtekin · Mobile & Frontend Engineer",
    "nav.ai": "AI", "nav.journey": "Experience", "nav.work": "Projects", "nav.game": "Game", "nav.contact": "Contact",

    "hero.eyebrow": "Mobile & Frontend Engineer · Istanbul",
    "hero.title": "Ataberk Kılınçtekin",
    "hero.tag1": "I build apps for iPhone, iPad",
    "hero.tag2": "and the web.",
    "hero.sub": "I'm at kloia, working in SwiftUI, UIKit and React. Apps I've worked on include Cepte Şok, Boost AI and UNHCR Service Advisor. I work spec-first with Claude Code and review every change before it ships.",
    "hero.cta1": "Projects",
    "hero.cta2": "Email me",
    "stat.years": "years in software",
    "stat.products": "live products",
    "stat.platforms": "platforms",

    "ai.eyebrow": "01 · AI",
    "ai.h1": "How I work",
    "ai.h2": "with AI.",
    "ai.lead": "Most of my code is written by AI agents in Claude Code, from a spec I write and approve first. I review every change before it goes in.",
    "ai.f1.t": "Spec", "ai.f1.b": "Written and approved before any code",
    "ai.f2.t": "Plan", "ai.f2.b": "Split into small, testable tasks",
    "ai.f3.t": "Build", "ai.f3.b": "Agents write the code, tests confirm it",
    "ai.f4.t": "Review", "ai.f4.b": "A separate agent checks the diff, then me",
    "ai.c1.t": "Agentic coding with Claude Code",
    "ai.c1.b": "Claude Code drafts screens, tests and refactors. I correct what's wrong and keep the architecture consistent.",
    "ai.c2.t": "Spec first, then code",
    "ai.c2.b": "Every feature starts with a written spec and a task plan. Code comes after both are approved.",
    "ai.c3.t": "Token-efficient by design",
    "ai.c3.b": "Small models search and read; larger ones plan and review. Exploration runs in sub-agents, so the main session stays small and burns fewer tokens.",
    "ai.c4.t": "Project memory",
    "ai.c4.b": "Decisions, pitfalls and setup notes live in a knowledge base the agents read before they start.",
    "ai.quote": "I'm responsible for every line that ships, whoever typed it.",
    "ai.i1.k": "Studying",
    "ai.i1.t": "AI architectures",
    "ai.i1.b": "I study how LLMs and multi-agent systems are built: transformers, agent design and running ML systems in production.",
    "ai.i2.k": "Open to",
    "ai.i2.t": "Automation projects",
    "ai.i2.b": "AI agents that take over repetitive work, workflow automation and UI test automation.",

    "journey.eyebrow": "02 · Experience",
    "journey.h1": "From industrial engineering",
    "journey.h2": "to mobile development.",
    "journey.y1": "2020",
    "journey.t1": "Process Development Engineer · Mert Döküm",
    "journey.b1": "Connected performance tracking to the Uyumsoft ERP, reported KPIs to the executive board each month and ran internal audits at three sites.",
    "journey.y2": "2021",
    "journey.t2": "Industrial Engineering · Marmara University",
    "journey.b2": "Bachelor's degree.",
    "journey.y3": "2022",
    "journey.t3": "ReactJS Developer · kloia",
    "journey.b3": "Built web projects with React and Redux Toolkit, with Material UI and Tailwind on the UI side.",
    "journey.y4": "2022",
    "journey.t4": "ReactJS Developer · Orsa",
    "journey.b4": "Built a video-conferencing web app, integrated third-party video services and rewrote legacy pages.",
    "journey.y5": "2023 · now",
    "journey.t5": "Frontend & Mobile Engineer · kloia",
    "journey.b5": "iPhone and iPad apps in SwiftUI and UIKit, plus frontend work on web projects.",
    "journey.from": "ERP & KPIs",
    "journey.to": "iOS & web",

    "tools.eyebrow": "03 · Stack",
    "tools.h1": "Tools I use",
    "tools.h2": "at work.",
    "tools.g1": "Mobile",
    "tools.g2": "Web",
    "tools.g3": "Backend & APIs",

    "work.eyebrow": "04 · Projects",
    "work.h1": "Apps I've worked on,",
    "work.h2": "all live today.",
    "work.store": "App Store ↗",
    "work.site": "Website ↗",
    "work.cepte.tag": "Retail · iOS",
    "work.cepte.b": "Şok Marketler's online shopping app for iPhone.",
    "work.boost.tag": "Education · AI · iOS",
    "work.boost.b": "Math help for exam prep. A student uploads a question and gets the solution step by step.",
    "work.unhcr.tag": "Humanitarian · iOS",
    "work.unhcr.b": "UNHCR's app for refugees and asylum-seekers in Turkey: rights, service locations and a chatbot.",
    "work.testgenie.tag": "Web platform",
    "work.testgenie.b": "Web platform. Details on the site.",

    "game.eyebrow": "05 · Side project",
    "game.h1": "A game",
    "game.h2": "I'm working on.",
    "game.line": "A mobile idle game built in Unity. Screenshots will come with the release.",
    "game.badge": "Not released yet",

    "contact.eyebrow": "06 · Contact",
    "contact.h1": "Hiring for mobile",
    "contact.h2": "or frontend?",
    "contact.sub": "I'm open to mobile, frontend and automation projects. Email is the fastest way to reach me.",
    "footer": "© 2026 Ataberk Kılınçtekin · Istanbul"
  },
  tr: {
    "meta.title": "Ataberk Kılınçtekin · Mobil ve Frontend Mühendisi",
    "nav.ai": "AI", "nav.journey": "Deneyim", "nav.work": "Projeler", "nav.game": "Oyun", "nav.contact": "İletişim",

    "hero.eyebrow": "Mobil ve Frontend Mühendisi · İstanbul",
    "hero.title": "Ataberk Kılınçtekin",
    "hero.tag1": "iPhone, iPad ve web için",
    "hero.tag2": "uygulamalar geliştiriyorum.",
    "hero.sub": "kloia'da SwiftUI, UIKit ve React kullanıyorum. Cepte Şok, Boost AI ve UNHCR Service Advisor üzerinde çalıştığım uygulamalardan birkaçı. Claude Code ile spec odaklı çalışıyorum; yayına çıkmadan önce her değişikliği inceliyorum.",
    "hero.cta1": "Projeler",
    "hero.cta2": "E-posta gönder",
    "stat.years": "yıl yazılım deneyimi",
    "stat.products": "yayında ürün",
    "stat.platforms": "platform",

    "ai.eyebrow": "01 · AI",
    "ai.h1": "AI ile",
    "ai.h2": "çalışma düzenim.",
    "ai.lead": "Kodumun büyük kısmını Claude Code'daki AI ajanları yazıyor. Önce spec'i ben yazıp onaylıyorum, içeri giren her değişikliği de inceliyorum.",
    "ai.f1.t": "Spec", "ai.f1.b": "Koddan önce yazılıp onaylanır",
    "ai.f2.t": "Plan", "ai.f2.b": "Küçük, test edilebilir görevlere bölünür",
    "ai.f3.t": "Kod", "ai.f3.b": "Ajanlar yazar, testler doğrular",
    "ai.f4.t": "İnceleme", "ai.f4.b": "Önce ayrı bir ajan, sonra ben incelerim",
    "ai.c1.t": "Claude Code ile agentic coding",
    "ai.c1.b": "Ekranların, testlerin ve refactor'ların ilk halini Claude Code çıkarıyor. Yanlışları ben düzeltiyorum, mimariyi ben tutarlı tutuyorum.",
    "ai.c2.t": "Önce spec, sonra kod",
    "ai.c2.b": "Her özellik yazılı bir spec ve görev planıyla başlıyor. Kod, ikisi de onaylandıktan sonra yazılıyor.",
    "ai.c3.t": "Token verimli çalışma",
    "ai.c3.b": "Arama ve okumayı küçük modeller, planlama ve incelemeyi büyük modeller yapıyor. Keşif işleri alt ajanlarda döndüğü için ana oturum küçük kalıyor, daha az token harcanıyor.",
    "ai.c4.t": "Proje hafızası",
    "ai.c4.b": "Kararlar, dikkat edilecek noktalar ve kurulum notları bir bilgi tabanında duruyor. Ajanlar işe başlamadan önce bunları okuyor.",
    "ai.quote": "Kodu kim yazmış olursa olsun, yayına çıkan her satırın sorumlusu benim.",
    "ai.i1.k": "Çalışıyorum",
    "ai.i1.t": "AI mimarileri",
    "ai.i1.b": "LLM'lerin ve çoklu ajan sistemlerinin nasıl kurulduğunu çalışıyorum: transformer yapısı, ajan tasarımı ve ML sistemlerini canlıda çalıştırmak.",
    "ai.i2.k": "Açığım",
    "ai.i2.t": "Otomasyon projeleri",
    "ai.i2.b": "Tekrarlayan işleri üstlenen AI ajanları, iş akışı otomasyonu ve UI test otomasyonu.",

    "journey.eyebrow": "02 · Deneyim",
    "journey.h1": "Endüstri mühendisliğinden",
    "journey.h2": "mobil geliştirmeye.",
    "journey.y1": "2020",
    "journey.t1": "Proses Geliştirme Mühendisi · Mert Döküm",
    "journey.b1": "Performans takibini Uyumsoft ERP'ye bağladım, yönetim kuruluna her ay KPI raporu sundum, üç lokasyonda iç denetim yaptım.",
    "journey.y2": "2021",
    "journey.t2": "Endüstri Mühendisliği · Marmara Üniversitesi",
    "journey.b2": "Lisans derecesi.",
    "journey.y3": "2022",
    "journey.t3": "ReactJS Geliştirici · kloia",
    "journey.b3": "React ve Redux Toolkit ile web projeleri geliştirdim, arayüzde Material UI ve Tailwind kullandım.",
    "journey.y4": "2022",
    "journey.t4": "ReactJS Geliştirici · Orsa",
    "journey.b4": "Görüntülü görüşme için bir web uygulaması geliştirdim, üçüncü parti video servislerini entegre ettim ve eski sayfaları yeniden yazdım.",
    "journey.y5": "2023 · bugün",
    "journey.t5": "Frontend ve Mobil Mühendis · kloia",
    "journey.b5": "SwiftUI ve UIKit ile iPhone ve iPad uygulamaları geliştiriyorum, web projelerinde de frontend tarafında çalışıyorum.",
    "journey.from": "ERP ve KPI",
    "journey.to": "iOS ve web",

    "tools.eyebrow": "03 · Teknolojiler",
    "tools.h1": "İşte kullandığım",
    "tools.h2": "teknolojiler.",
    "tools.g1": "Mobil",
    "tools.g2": "Web",
    "tools.g3": "Backend ve API",

    "work.eyebrow": "04 · Projeler",
    "work.h1": "Üzerinde çalıştığım",
    "work.h2": "yayındaki uygulamalar.",
    "work.store": "App Store ↗",
    "work.site": "Siteye git ↗",
    "work.cepte.tag": "Perakende · iOS",
    "work.cepte.b": "Şok Marketler'in iPhone için online alışveriş uygulaması.",
    "work.boost.tag": "Eğitim · AI · iOS",
    "work.boost.b": "Sınava hazırlanan öğrenciler için matematik uygulaması. Öğrenci soruyu yüklüyor, çözümü adım adım görüyor.",
    "work.unhcr.tag": "İnsani yardım · iOS",
    "work.unhcr.b": "UNHCR'ın Türkiye'deki mülteci ve sığınmacılar için uygulaması: haklar, hizmet noktaları ve bir sohbet botu.",
    "work.testgenie.tag": "Web platformu",
    "work.testgenie.b": "Web platformu. Detaylar sitede.",

    "game.eyebrow": "05 · Yan proje",
    "game.h1": "Üzerinde çalıştığım",
    "game.h2": "bir oyun.",
    "game.line": "Unity ile geliştirilen bir mobil idle oyun. Ekran görüntüleri çıkışla birlikte gelecek.",
    "game.badge": "Henüz yayınlanmadı",

    "contact.eyebrow": "06 · İletişim",
    "contact.h1": "Mobil veya frontend",
    "contact.h2": "geliştirici mi arıyorsunuz?",
    "contact.sub": "Mobil, frontend ve otomasyon projelerine açığım. Bana en hızlı e-postayla ulaşırsınız.",
    "footer": "© 2026 Ataberk Kılınçtekin · İstanbul"
  }
};
