const COPY = {
  en: {
    "meta.title": "Ataberk Kılınçtekin · Mobile & Frontend Engineer",
    "nav.mobile": "Mobile", "nav.ai": "AI", "nav.web": "Web", "nav.game": "Game", "nav.contact": "Contact",

    "hero.role": "Mobile & frontend engineer, Istanbul",
    "hero.sub": "I build apps for iPhone, iPad and the web.",
    "hero.cta1": "Projects",
    "hero.cta2": "Email me",
    "x.screen": "Screen", "x.tree": "view tree", "x.code": "Swift", "x.net": "Network", "x.data": "Data",

    "mobile.h": "Mobile",
    "mobile.role": "Frontend & Mobile Engineer, kloia",
    "mobile.when": "2023–now",
    "work.store": "App Store",
    "work.cepte.tag": "Retail",
    "work.cepte.b": "Şok Marketler's online shopping app for iPhone.",
    "work.boost.tag": "Education, AI",
    "work.boost.b": "Math help for exam prep. A student uploads a question and gets the solution step by step.",
    "work.unhcr.tag": "Humanitarian",
    "work.unhcr.b": "UNHCR's app for refugees and asylum-seekers in Turkey: rights, service locations and a chatbot.",
    "tools.label": "Tools",

    "ai.h": "AI",
    "ai.lead": "Most of my code is written by AI agents in Claude Code.",
    "line.spec": "Spec", "line.plan": "Plan", "line.build": "Build", "line.review": "Review", "line.ship": "Ship",
    "ai.tokens.t": "Token-efficient by design",
    "ai.tokens.b": "Small models search and read; larger ones plan and review. Exploration runs in sub-agents, so the main session stays small.",
    "ai.memory.t": "Project memory",
    "ai.memory.b": "Decisions, pitfalls and setup notes live in a knowledge base the agents read before they start.",
    "ai.auto.t": "Automation",
    "ai.auto.b": "Agents that take over repetitive work, plus workflow and UI test automation.",
    "ai.study.t": "Studying AI architectures",
    "ai.study.b": "How LLMs and multi-agent systems are built: transformers, agent design and running ML systems in production.",

    "web.h": "Web",
    "web.kloia.t": "ReactJS Developer, kloia",
    "web.kloia.b": "Built web projects with React and Redux Toolkit, with Material UI and Tailwind on the UI side.",
    "web.orsa.t": "ReactJS Developer, Orsa",
    "web.orsa.b": "Built a video-conferencing web app, integrated third-party video services and rewrote legacy pages.",
    "web.testgenie.b": "Behavioral monitoring platform",
    "web.topbasdemir.b": "Freelance, steel producer",
    "web.topbasisi.b": "Freelance, heating and cooling systems",
    "web.albaltd.b": "Freelance, steel industry and trade",

    "bg.h": "Before software",
    "bg.mert.t": "Process Development Engineer, Mert Döküm",
    "bg.mert.b": "Connected performance tracking to the Uyumsoft ERP, reported KPIs to the executive board each month and ran internal audits at three sites.",
    "bg.edu.t": "Industrial Engineering, Marmara University",
    "bg.edu.b": "Bachelor's degree.",

    "game.h": "Game",
    "game.line": "A mobile idle game I'm working on, built in Unity. Screenshots will come with the release.",
    "game.badge": "Not released yet",

    "contact.h": "Hiring for mobile or frontend?",
    "contact.sub": "I'm open to mobile, frontend and automation projects. Email is the fastest way to reach me.",
    "footer": "© 2026 Ataberk Kılınçtekin, Istanbul"
  },
  tr: {
    "meta.title": "Ataberk Kılınçtekin · Mobil ve Frontend Mühendisi",
    "nav.mobile": "Mobil", "nav.ai": "AI", "nav.web": "Web", "nav.game": "Oyun", "nav.contact": "İletişim",

    "hero.role": "Mobil ve frontend mühendisi, İstanbul",
    "hero.sub": "iPhone, iPad ve web için uygulamalar geliştiriyorum.",
    "hero.cta1": "Projeler",
    "hero.cta2": "E-posta gönder",
    "x.screen": "Ekran", "x.tree": "görünüm ağacı", "x.code": "Swift", "x.net": "Ağ", "x.data": "Veri",

    "mobile.h": "Mobil",
    "mobile.role": "Frontend ve Mobil Mühendis, kloia",
    "mobile.when": "2023–bugün",
    "work.store": "App Store",
    "work.cepte.tag": "Perakende",
    "work.cepte.b": "Şok Marketler'in iPhone için online alışveriş uygulaması.",
    "work.boost.tag": "Eğitim, AI",
    "work.boost.b": "Sınava hazırlanan öğrenciler için matematik uygulaması. Öğrenci soruyu yüklüyor, çözümü adım adım görüyor.",
    "work.unhcr.tag": "İnsani yardım",
    "work.unhcr.b": "UNHCR'ın Türkiye'deki mülteci ve sığınmacılar için uygulaması: haklar, hizmet noktaları ve bir sohbet botu.",
    "tools.label": "Araçlar",

    "ai.h": "AI",
    "ai.lead": "Kodumun büyük kısmını Claude Code'daki AI ajanları yazıyor.",
    "line.spec": "Spec", "line.plan": "Plan", "line.build": "Kod", "line.review": "İnceleme", "line.ship": "Yayın",
    "ai.tokens.t": "Token verimli çalışma",
    "ai.tokens.b": "Arama ve okumayı küçük modeller, planlama ve incelemeyi büyük modeller yapıyor. Keşif işleri alt ajanlarda döndüğü için ana oturum küçük kalıyor.",
    "ai.memory.t": "Proje hafızası",
    "ai.memory.b": "Kararlar, dikkat edilecek noktalar ve kurulum notları bir bilgi tabanında duruyor. Ajanlar işe başlamadan önce bunları okuyor.",
    "ai.auto.t": "Otomasyon",
    "ai.auto.b": "Tekrarlayan işleri üstlenen ajanlar, iş akışı ve UI test otomasyonu.",
    "ai.study.t": "AI mimarileri üzerine çalışıyorum",
    "ai.study.b": "LLM'lerin ve çoklu ajan sistemlerinin nasıl kurulduğu: transformer yapısı, ajan tasarımı ve ML sistemlerini canlıda çalıştırmak.",

    "web.h": "Web",
    "web.kloia.t": "ReactJS Geliştirici, kloia",
    "web.kloia.b": "React ve Redux Toolkit ile web projeleri geliştirdim, arayüzde Material UI ve Tailwind kullandım.",
    "web.orsa.t": "ReactJS Geliştirici, Orsa",
    "web.orsa.b": "Görüntülü görüşme için bir web uygulaması geliştirdim, üçüncü parti video servislerini entegre ettim ve eski sayfaları yeniden yazdım.",
    "web.testgenie.b": "Davranışsal izleme platformu",
    "web.topbasdemir.b": "Freelance, demir çelik üreticisi",
    "web.topbasisi.b": "Freelance, ısıtma ve soğutma sistemleri",
    "web.albaltd.b": "Freelance, demir çelik sanayi ve ticaret",

    "bg.h": "Yazılımdan önce",
    "bg.mert.t": "Proses Geliştirme Mühendisi, Mert Döküm",
    "bg.mert.b": "Performans takibini Uyumsoft ERP'ye bağladım, yönetim kuruluna her ay KPI raporu sundum, üç lokasyonda iç denetim yaptım.",
    "bg.edu.t": "Endüstri Mühendisliği, Marmara Üniversitesi",
    "bg.edu.b": "Lisans derecesi.",

    "game.h": "Oyun",
    "game.line": "Üzerinde çalıştığım, Unity ile geliştirilen bir mobil idle oyun. Ekran görüntüleri çıkışla birlikte gelecek.",
    "game.badge": "Henüz yayınlanmadı",

    "contact.h": "Mobil veya frontend geliştirici mi arıyorsunuz?",
    "contact.sub": "Mobil, frontend ve otomasyon projelerine açığım. Bana en hızlı e-postayla ulaşırsınız.",
    "footer": "© 2026 Ataberk Kılınçtekin, İstanbul"
  }
};
